### ISSUE TITLE
Missing argument on queue_declare and  pika.exceptions.ChannelClosedByBroker with RESOURCE_LOCKED

### ISSUE THREAD

**Issue by Bumerang47** [danidee10/Chatire#11]
Hello, i try use your example from tutorial and i have some trouble.
> File "websocket.py", line 16, in <module>
> result = channel.queue_declare(exclusive=True)
> TypeError: queue_declare() missing 1 required positional argument: 'queue'

For solution i use `exchange` how queue argument.
`result = channel.queue_declare(exchange, exclusive=True)`
and after this if i open multiple connections i have next error:

> Traceback (most recent call last):
>   File "./websocket.py", line 27, in application
>     result = channel.queue_declare(exchange, exclusive=True)
>   File "/home/alexul/.pyenv/versions/gv_new/lib/python3.6/site-packages/pika/adapters/blocking_connection.py", line 2498, in queue_declare
>     self._flush_output(declare_ok_result.is_ready)
>   File "/home/alexul/.pyenv/versions/gv_new/lib/python3.6/site-packages/pika/adapters/blocking_connection.py", line 1331, in _flush_output
>     raise self._closing_reason  # pylint: disable=E0702
> pika.exceptions.ChannelClosedByBroker: (405, "RESOURCE_LOCKED - cannot obtain exclusive access to locked queue 'eb08e969403a43c' in vhost '/'")
> 
Do you have some thinks about solution this?
<details><summary>pip freeze</summary>
<p>

> 
> $ pip freeze
> amqp==2.4.2
> Babel==2.6.0
> billiard==3.6.0.0
> celery==4.3.0
> certifi==2018.11.29
> chardet==3.0.4
> choicesenum==0.5.3
> coreapi==2.3.3
> coreschema==0.0.4
> Django==2.1.5
> django-cors-headers==2.5.2
> django-filter==2.1.0
> django-notifs==2.6.2
> django-phonenumber-field==2.2.0
> djangorestframework==3.9.1
> djangorestframework-jwt==1.11.0
> entrypoints==0.3
> flake8==3.7.7
> gevent==1.4.0
> greenlet==0.4.15
> idna==2.8
> itypes==1.1.0
> Jinja2==2.10
> kombu==4.5.0
> MarkupSafe==1.1.0
> mccabe==0.6.1
> phonenumbers==8.10.5
> pika==1.0.0
> Pillow==5.4.1
> pycodestyle==2.5.0
> pyflakes==2.1.1
> PyJWT==1.7.1
> pytz==2018.9
> remote-pdb==1.3.0
> requests==2.21.0
> six==1.12.0
> uritemplate==3.0.0
> urllib3==1.24.1
> uWSGI==2.0.18
> vine==1.3.0

</p>
</detail>

**Comment by Bumerang47** [comment]
so, it cleary that is reason in next version pika and now queue_declare required send the queue. On the first try it somehow wasn't help me. But now i second try and it help me, just use `result = channel.queue_declare('', exclusive=True)`

As far as I understand we open a unique channel to RabbitMQ for the each connection.
